# Generated by Django 5.1 on 2024-09-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_lecture_slug_alter_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, default='DOFq6', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
