# Generated by Django 5.1 on 2024-09-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_course_thumbnail_alter_lecture_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='length',
            field=models.CharField(default='1hr 20min', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, default='vwq2r', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.course'),
        ),
    ]
