# Generated by Django 5.1 on 2024-09-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_lecture_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_line_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='courses')),
            ],
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to='album'),
        ),
    ]
