# Generated by Django 5.1 on 2024-09-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_paidcourse_alter_albumimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaidCourse',
            new_name='PremiumCourse',
        ),
    ]
