# Generated by Django 5.1 on 2024-09-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_rename_paidcourse_premiumcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourse',
            name='duration',
            field=models.CharField(default='3 months', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumcourse',
            name='elligibility',
            field=models.TextField(default='adfadf\nqerqer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumcourse',
            name='mode',
            field=models.CharField(default='Live + Recorded', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumcourse',
            name='why_learn',
            field=models.TextField(default='adfadf'),
            preserve_default=False,
        ),
    ]
