# Generated by Django 5.1 on 2024-09-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_premiumcourse_duration_premiumcourse_elligibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourse',
            name='key_highlights',
            field=models.TextField(default='adfadf\nqerqerqer\nadfadfadf'),
            preserve_default=False,
        ),
    ]
