# Generated by Django 5.1 on 2024-09-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_premiumcourse_key_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourse',
            name='length',
            field=models.CharField(default='70+ lectures', max_length=100),
        ),
        migrations.AlterField(
            model_name='premiumcourse',
            name='duration',
            field=models.CharField(default='3 months', max_length=50),
        ),
        migrations.AlterField(
            model_name='premiumcourse',
            name='mode',
            field=models.CharField(default='Live + Recorded', max_length=100),
        ),
    ]
