# Generated by Django 5.1 on 2024-10-09 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_premiumcourse_length_alter_premiumcourse_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
