# Generated by Django 5.1 on 2024-10-10 06:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_albumimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumcourse',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
