# Generated by Django 5.1 on 2026-06-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_premiumcourse_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('r2_key', models.CharField(help_text='Path to the .m3u8 file in R2, e.g. courses/slug/lecture-1/index.m3u8', max_length=500)),
                ('length', models.CharField(default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.premiumcourse')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
