# Generated by Django 5.1 on 2024-10-17 15:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_premiumcourse_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('one_line_description', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('steps', models.TextField()),
                ('price', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
