# Generated by Django 5.1 on 2024-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
