# Generated by Django 5.1 on 2026-06-20 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_premiumlecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumlecture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
