# Generated by Django 5.1 on 2026-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_premiumlecture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumlecture',
            name='aes_key',
            field=models.CharField(blank=True, help_text='Hex-encoded 16-byte AES-128 key from key generation step', max_length=32),
        ),
    ]
