# Generated by Django 5.1 on 2026-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_enrolledcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumlecture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
