# Generated by Django 5.1 on 2026-06-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_premiumlecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumlecture',
            name='description',
            field=models.TextField(default='This is some default description.'),
        ),
    ]
