# Generated by Django 5.1 on 2026-07-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_jaapsession_jaapsessionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaapsession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Set to a future time to show this session as upcoming before it goes live.', null=True),
        ),
        migrations.AlterField(
            model_name='jaapsession',
            name='god_name',
            field=models.CharField(default='Jai Shree Hari', max_length=100),
        ),
    ]
