# Generated by Django 5.1 on 2026-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_jaapsession_scheduled_at_alter_jaapsession_god_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaapsessionparticipant',
            name='last_mala_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
