# Generated by Django 5.1 on 2026-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_jaapsessionparticipant_last_mala_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourse',
            name='striked_price',
            field=models.IntegerField(blank=True, help_text='Original price shown struck-through above the current offer price. Leave blank to hide.', null=True),
        ),
        migrations.AlterField(
            model_name='premiumcourse',
            name='price',
            field=models.IntegerField(help_text='Current offer price shown to students.'),
        ),
    ]
