# Generated by Django 5.1 on 2026-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_premiumcourse_striked_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcourse',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo courses are only shown to accounts whose email is in DEMO_ACCOUNT_EMAILS.'),
        ),
        migrations.AlterField(
            model_name='premiumcourse',
            name='elligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premiumcourse',
            name='price',
            field=models.IntegerField(help_text='Actual price shown to users.'),
        ),
    ]
